const mongoose = require("mongoose");

const categorySchema = new mongoose.Schema({
  name: {
    type: String,
    required: true,
  },
  code: {
    type: String,
    required: true,
    unique: true
  },
});

/**
 * @swagger
 * components:
 *   schemas:
 *     Category:
 *       type: object
 *       properties:
 *         _id:
 *           type: string
 *           format: objectId
 *           description: Autogenerated ObjectId for each category.
 *         name:
 *           type: string
 *           description: Name of the category.
 *         code:
 *           type: string
 *           description: Code of the category.
 *       required:
 *         - name
 *         - code
 */

module.exports = mongoose.model("Category", categorySchema)