const mongoose = require("mongoose");

const productSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true,
  },
  price: {
    type: Number,
    required: true,
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
  updatedAt: {
    type: Date,
    default: Date.now,
  },
  category: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Category",
    required: true,
  },
  description: {
    type: String,
  },
  images: {
    type: [String],
  },
  status: {
    type: String,
    enum: ["active", "inactive"],
    default: "active",
  },
  variants: {
    type: [
      {
        size: {
          type: String,
          required: true,
        },
        color: {
          type: [
            {
              name: {
                type: String,
                required: true,
              },
              code: {
                type: String,
                required: true,
              },
              quantity: {
                type: Number,
                required: true,
              },
            }
          ],
          required: true,
        },
        quantity: {
          type: Number,
          required: true,
        },
      },
    ],
  },
});

module.exports = mongoose.model("Product", productSchema)

/**
 * @swagger
 * components:
 *   schemas:
 *     Product:
 *       type: object
 *       properties:
 *         _id:
 *           type: string
 *           format: objectId
 *           description: Autogenerated ObjectId for each product.
 *         name:
 *           type: string
 *           description: Name of the product.
 *         price:
 *           type: number
 *           description: Price of the product.
 *         category:
 *           type: string
 *           description: Category of the product.
 *         description:
 *           type: string
 *           description: Description of the product.
 *         images:
 *           type: array
 *           description: Images of the product.
 *         status:
 *           type: string
 *           description: Status of the product.
 *         variants:
 *           type: array
 *           description: Variants of the product, type of size and color and quantity.
 *         createdAt:
 *           type: string
 *           format: date
 *           description: Date of creation of the product.
 *         updatedAt:
 *           type: string
 *           format: date
 *           description: Date of last update of the product.
 *       required:
 *         - name
 *         - price
 *         - category
 */