const mongoose = require("mongoose");

const transactionSchema = new mongoose.Schema({
  totalPrice: {
    type: Number,
    required: true,
  },
  discount: {
    type: Number,
    default: 0,
  },
  createdAt: {
    type: Date,
    default: Date.now,
  },
  updatedAt: {
    type: Date,
    default: Date.now,
  },
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "User",
    required: true,
  },
  products: {
    type: [
      {
        prod: {
          type: mongoose.Schema.Types.ObjectId,
          ref: "Product",
          required: true,
        },
        size: {
          type: String,
        },
        color: {
          type: String,
        },
        quantity: {
          type: Number,
          required: true,
        },
      }
    ],
    required: true,
  },
  status: {
    type: String,
    default: "init",
    enum: ["init", "process", "success", "failed"],
  }
});

module.exports = mongoose.model("Transaction", transactionSchema);

/**
 * @swagger
 * components:
 *   schemas:
 *     Transaction:
 *       type: object
 *       properties:
 *         _id:
 *           type: string
 *           format: objectId
 *           description: Autogenerated ObjectId for each transaction.
 *         totalPrice:
 *           type: number
 *           description: Total price of the transaction.
 *         discount:
 *           type: number
 *           description: Discount of the transaction.
 *         createdAt:
 *           type: string
 *           format: date-time
 *           description: Date and time when the transaction was created.
 *         updatedAt:
 *           type: string
 *           format: date-time
 *           description: Date and time when the transaction was updated.
 *         user:
 *           type: string
 *           description: User of the transaction.
 *         products:
 *           type: array
 *           description: Products of the transaction, including product ID, size, color, and quantity.
 *         status:
 *           type: string
 *           description: Status of the transaction.
 * 
 */